FROM oven/bun:1 as base

# 작업 디렉토리 설정
WORKDIR /usr/src/app

# package.json 파일 복사
COPY package.json ./

# bun을 사용하여 의존성 설치
RUN bun install

# 나머지 파일 복사
COPY . .

# 사용자 설정
USER bun

# 포트 3000번 개방
EXPOSE 3000/tcp

# 컨테이너 실행시 bun dev 명령어 실행
CMD bun dev